### ISSUE TITLE
Zotero 4 compatibility

### ISSUE THREAD

**Issue by sjpfenninger** [robintw/AutoZotBib#3]
To make the plugin work under Zotero 4, I simply changed the maxVersion bounds in `install.rdf`:

`<em:maxVersion>3.0.*</em:maxVersion>`

to:

`<em:maxVersion>4.*</em:maxVersion>`

Superficial testing confirms that everything appears to work fine under version 4.

**Comment by adam3smith** [comment]
I've also tested this and have a pull request here:
https://github.com/robintw/AutoZotBib/pull/4

**Comment by robintw** [comment]
Thanks for the pull request, and sorry for the delay. The updated version is now available for download from http://www.rtwilson.com/academic/autozotbib.

A completely new version of AutoZotBib will hopefully be released within the next month or two (it's almost finished, just trying to iron out some bugs) - this will be a lot faster for large libraries and should fix most of the complaints with the current version.
